<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeuDiarioSENAC.Data\MeuDiarioSENAC.Data.csproj" />
    <ProjectReference Include="..\MeuDiarioSENAC.Model\MeuDiarioSENAC.Model.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
